<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AssemblyName>Updater</AssemblyName>
	<PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\Core\Core\Core.csproj" />
    <ProjectReference Include="..\SMOO.Updater.Lib\SMOO.Updater.Lib.csproj" />
  </ItemGroup>

</Project>
